# Site settings
title: Branko Tomić
email: klomontes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I’m Branko, UI/UX designer and frontend developer. I am a part of awesome
  crew at SpiceFactory. I occasionaly think of writing a blog post.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brankotomic.com" # the base hostname & protocol for your site
github_username:  klomontes

# Build settings
markdown: kramdown

sass:
  style: compressed
